### ISSUE TITLE
architectury port todos

### ISSUE THREAD

**Issue by CodeF53** [CodeF53/Horse-Buff#30]
~~embed autoconfig in forge (cursed, Ran is doing this)~~ Not allowed to do :(
- [x] fix `horsebuff.mixins.json` not getting refmap appended in output jar (black magic, Ran is doing this)
- [x] forge + fabric in one jar (cursed, Ran is doing this)
  - [x] ~~fork https://github.com/Ran-helo/DHJarMerger and change hardcoded stuff from LOD to HorseBuff~~ 
  Using https://github.com/PacifistMC/Forgix
- [x] wait for [Jar in Jar to be merged into Architectury](https://github.com/architectury/architectury-loom/pull/93) 
- [x] implement JarJar so autoconfig dependency is consistent across fabric and forge

**Comment by Ran-helo** [comment]
No need to fork https://github.com/Ran-helo/DHJarMerger
am working on https://github.com/PacifistMC/Forgix which will replace DHJarMerger and will be better in everyway

**Comment by CodeF53** [comment]
Fix whatever hell code is going wrong.

**Comment by CodeF53** [comment]
Supporting forge is not in scope given my free time now
