### ISSUE TITLE
Horses don't flash red when taking damage

### ISSUE THREAD

**Issue by spysandwiches** [CodeF53/Horse-Buff#33]
Horses won't flash red when taking damage from any source.
Probably related, jeb_ doesn't effect them even when enabled in config.

Minecraft: 1.19.2
Fabric Version: 0.14.9
HorseBuff Version: 2.0.1
JDK 17.0.1
No other mods installed

**Comment by mistrk7** [comment]
Seems to be fixed now, at least on Sodium

**Comment by CodeF53** [comment]
Fixed in vanilla too
