### ISSUE TITLE
Skeleton horses cull incorrectly

### ISSUE THREAD

**Issue by SplendidAlakey** [CodeF53/Horse-Buff#35]
**MC** 1.19.2
**FAPI** 0.67.1
**HorseBuff** 2.0.1

Skeleton Horses get incorrectly culled when HorseBuff is installed. As you can see below, the insides of skeleton horses are completely transparent.

Without HorseBuff:
![2022-11-28_10 23 20](https://user-images.githubusercontent.com/86702831/204248898-1f1d3543-93a8-4bde-b360-2de636a1e812.png)
![2022-11-28_10 23 34](https://user-images.githubusercontent.com/86702831/204248919-1e24df9f-330b-4096-9be2-1a1837e0cadf.png)

With HorseBuff:
![2022-11-28_10 51 49](https://user-images.githubusercontent.com/86702831/204248981-2d6a173d-0430-4990-9d4e-b7b8b87b2543.png)
![2022-11-28_10 51 52](https://user-images.githubusercontent.com/86702831/204248997-df9460b4-3794-4f76-9758-9126c102cd43.png)

**Comment by CodeF53** [comment]
This is a unfortunate downside to the way I modify horse rendering.

Its either this or horrible issues with transparency.

I have tried all the other built in rendering modes and none of them fix this while also supporting rendering transparent blocks behind horses.

I would have to make my own render mode to fix this, which is unfortunately far out of scope for this project.

**Comment by CodeF53** [comment]
See #20 for the issues the other render modes cause
