### ISSUE TITLE
Some images in description are returning HTTP 403 as a result of indirect requests

### ISSUE THREAD

**Issue by James103** [CodeF53/Horse-Buff#39]
Some of the images in the mod's description (https://modrinth.com/mod/horsebuff) are not loading, for the following reason:

* The images are being requested through a caching service, example: `https://wsrv.nl/?url=https%3A%2F%2Fimgur.com%2FQTk8w33.gif`
* These requests fail because the upstream imgur service has blocked the caching service: `{"status":"error","code":404,"message":"The requested URL returned error: 403"}`

Changing the URLs to fetch the image directly from imgur (`https://imgur.com/QTk8w33.gif` in this example) works properly.

**Comment by CodeF53** [comment]
I believe this is a case of modrinth caching my images for me, as my markdown already directly links to imgur as you suggested. You can confirm this yourself as the Readme.md here uses the same markdown as the one on the modrinth page.

**Comment by James103** [comment]
> I believe this is a case of modrinth caching my images for me

Can confirm this is the case. Checking [the source code for the Modrinth backend](https://github.com/modrinth/knossos/blob/130ece3d2e5e49a1c901c967cc3d40fbcaa3113c/helpers/parse.js#L109), I find the following:
* There is a list of hostnames Modrinth allows directly serving content from, which includes `i.imgur.com` among others but not plain `imgur.com`.
* If the hostname of the URL does not exactly match one of the hostnames from the list, Modrinth prepends `https://wsrv.nl/?url=` to the URL, effectively forcing the image to be cached through a third-party service instead of being served directly.
* From my own testing, links of the form `https://imgur.com/QTk8w33.gif` redirect to `https://i.imgur.com/QTk8w33.gif` (the hostname changes from `imgur.com` to `i.imgur.com`.

Therefore, I'd recommend updating links of the form `https://imgur.com/QTk8w33.gif` by changing `imgur.com` to `i.imgur.com` so Modrinth does not force the images to be cached through a third party `wsrv.nl`.

**Comment by CodeF53** [comment]
Fixed for awhile now, but I finally pushed the changed readme
