### ISSUE TITLE
Horses occasonally get sent to wrong coordinates when traveling through nether portals.

### ISSUE THREAD

**Issue by jh34ghu43gu** [CodeF53/Horse-Buff#41]
Was riding my donkey through a nether side portal to the overworld and when I went through I didn't have my donkey and couldn't interact with blocks, when I relogged i was back on the donkey but falling into the void (in the overworld).

The overworld platform was made of top slabs at y-63, bottom of the portal at the same level. Netherside portal was at y=2 or 3. I think it might be related to the portal cooldown mobs have? When I tried again with another donkey (this time dismounting when going through portals) the donkey wasn't yet able to go through the portal which would have been the same case for the one that got bugged.

Server and client using 1.19.4 v2.0.4

**Comment by CodeF53** [comment]
I will try my best to fix this.

Was this at very large x/z coordinates? I have experienced something similar in development of the mod when that was the case, but I thought I fixed it.

**Comment by CodeF53** [comment]
It would also be helpful if you could find the log file for when you exited the portal while mounted

**Comment by jh34ghu43gu** [comment]
> Was this at very large x/z coordinates?

No, the overworld coords would have been around -100 and -1000.

> It would also be helpful if you could find the log file for when you exited the portal while mounted

Not my server but I have asked my friend for them, I'm going to work rn, hopefully they will respond before I'm off.

**Comment by jh34ghu43gu** [comment]
Update: our logs had nothing useful, only my disconnect, reconnect, and death message. I'll try to recreate it in single player and send you a world download if I remember after work today.

**Comment by jh34ghu43gu** [comment]
I can't replicate in single player unfortunately, I will try to get debug logs turned on when we next play together and try to sacrifice another donkey to the void to see if we can get some more information. Sorry I can't provide much more info.

Here's the exact portal coords 132 -63 248, 16 4 31 and  -94 -63 -966, -10 3 -120 (overworld, nether). The nether portals and first overworld portal had bottom slabs surrounding it and the 2nd overworld portal had top slabs on level with the portal block.

**Comment by CodeF53** [comment]
That won't be necessary.
I think I have enough info now

**Comment by CodeF53** [comment]
I tried, I can't recreate it.
https://youtu.be/lOdtYnJ4Wfo

**Comment by jh34ghu43gu** [comment]
That's ok, we stopped playing that world and I don't think it happened again so maybe just some rare funkyness. /shrug

**Comment by CodeF53** [comment]
I have refactored the portal horse code, so in theory this should never happen again.

**Comment by CodeF53** [comment]
Closed in 1.21
