### ISSUE TITLE
Is this supposed to work with mounts from Mythic Mounts?

### ISSUE THREAD

**Issue by allanonmage** [CodeF53/Horse-Buff#44]
Based on the way the mounts in Mythic Mounts work with other horse-related mods, I expected them to work with your mod.  So far, going through portals work, but the fade does not, so it's a mixed bag.  Do you want to add support for mounts in general, or should I ask them to add support for your mod?

https://www.curseforge.com/minecraft/mc-mods/mythic-mounts

**Comment by CodeF53** [comment]
I can't read their source code, so I have no idea why it wouldn't work.

My best guess is that they use some custom renderer.

**Comment by CodeF53** [comment]
The the Mythic Mounts models are rendered/animated using GeckoLib, so the mounts use an extension of their renderer class GeoEntityRenderer. 

So my mixin into the vanilla renderer doesn't apply to them.

If I ever feel like adding support, I got the developer to send me their source code for rendering.

[discord server](https://discord.gg/ZNMECpNpE9) [message in discord with the source code](https://discord.com/channels/866350560416497695/1119141035952574534/1120195042745798718)
(this mainly serves as a note to myself)

**Comment by CodeF53** [comment]
Adding would require integration with GeckoLib, which I don't want to add as a dependency.
