### ISSUE TITLE
Enhancement: Make Player Inventory Keyboard Shortcut Changeable

### ISSUE THREAD

**Issue by muhammedesadcomert** [CodeF53/Horse-Buff#45]
The related [code](https://github.com/CodeF53/Horse-Buff/blob/4a69656e655a3acba3856b8e056630b2217e610b/src/main/java/net/F53/HorseBuff/mixin/Client/InventoryAccessor.java#L26)

**Comment by CodeF53** [comment]
https://modrinth.com/mod/horsebuff/version/2.1.3
