### ISSUE TITLE
Bug: Chests Don't Show Behind the Invisible Horse

### ISSUE THREAD

**Issue by muhammedesadcomert** [CodeF53/Horse-Buff#46]
![image](https://github.com/CodeF53/Horse-Buff/assets/46245749/46ee922f-b1ba-4934-b630-3b645076c6c6)

**Comment by CodeF53** [comment]
This is an issue with Minecraft's handling of semi-transparent objects.

There are 2 fixes:

1. Set Maximum transparency to 100 inside Client > Horse Fade

https://github.com/CodeF53/Horse-Buff/assets/37855219/7c8f3236-708f-420d-9616-4a078eb6aaf1

2. Set Graphics to `Fabulous!` (the only thing Fabulous does differently than Fancy is fix this bug)

https://github.com/CodeF53/Horse-Buff/assets/37855219/4cc2aa7b-6f53-41e2-a81f-68d6aecfe627

Unless I want to implement my own renderer, this isn't something I can fix.

**Comment by muhammedesadcomert** [comment]
Wow! I wasn't expecting an answer like this. Thanks for the explanation.

This issue can stay open, I really want to do something about this.

**Comment by CodeF53** [comment]
Good luck

**Comment by CodeF53** [comment]
@muhammedesadcomert do you have a discord so we can quickly discuss what changes you are making?

I want to make sure I don't step on your toes as we are both working on this.

**Comment by muhammedesadcomert** [comment]
> @muhammedesadcomert do you have a discord so we can quickly discuss what changes you are making?
> 
> I want to make sure I don't step on your toes as we are both working on this.

Hey! This is my username: anengineerman

Lastly, I cleaned some garbage and updated to the version 1.19.4 release.
Currently, I am planning to update mod 1.20 and resolve some open issues.

**Comment by CodeF53** [comment]
Set graphics quality to Fabulous
