### ISSUE TITLE
Why is Mod Menu a hard requirement if this mod can work server-side only?

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [CodeF53/Horse-Buff#5]
Sorry if it's a stupid question, but as far as I understand Mod Menu is only needed for an optional ability to modify some mod's settings in-game. However, you made it a hard requirement for your mod, which means the server won't start without it. Could that be changed?

**Comment by CodeF53** [comment]
I am an idiot, will patch in next release.
