### ISSUE TITLE
Crash with portal linking mod

### ISSUE THREAD

**Issue by Rozbiynk** [CodeF53/Horse-Buff#52]
![изображение](https://github.com/CodeF53/Horse-Buff/assets/95433246/33a32e0d-ba38-4153-a977-2a131c5e4731)
It happens when im go through portal while mounting horse

**Comment by Rozbiynk** [comment]
it just kick me but doesnt crash server

**Comment by Rozbiynk** [comment]
https://mclo.gs/4u43hro

**Comment by CodeF53** [comment]
> also, is it normal that i can go through portal while im in the boat?

Yes, the portal patch only applies to AbstractHorseEntities because otherwise it could adversely effect various farms. For example: many portal based mob farms will use a boat with an entity inside to quickly push entities out of the portal on the receiving side.

**Comment by CodeF53** [comment]
Regarding the crash, it seems the other mod is to blame, as it assumes something will always be a portal block, when in this case, it is air.

I would open an issue on their github instead.

Also it would be helpful if you could actually link to the mod, as I can't find it.

**Comment by CodeF53** [comment]
Looking further into this. It's something they would have to fix, not me.

**Comment by CodeF53** [comment]
HorseBuff no longer does portal code because they fixed the issue in 1.21
