### ISSUE TITLE
error during launch with EMF (& ETF)

### ISSUE THREAD

**Issue by dadoirie** [CodeF53/Horse-Buff#53]
Having Horse Buff with [EMF](https://modrinth.com/mod/entity-model-features) (& [ETF](https://modrinth.com/mod/entitytexturefeatures) since EMF's depends on it) makes console throws a huge error during launch.

https://mclo.gs/fmhXDRN (starting at line [227](https://mclo.gs/fmhXDRN#L227))

**Comment by CodeF53** [comment]
While I can recreate the error happening in console, it doesn't appear to have any effect on any of the functionality for either mod.

[Fresh Animations](https://www.curseforge.com/minecraft/texture-packs/fresh-animations) seems to work just fine despite the error.

Unless you can find something that actually breaks, or the game crashes, I don't think this is a problem. 

Feel free to reopen the issue if you do encounter crashes or bugs.
