### ISSUE TITLE
[suggestion] block suffocation when mounted

### ISSUE THREAD

**Issue by dadoirie** [CodeF53/Horse-Buff#54]
it is a well known old vanilla bug when riding a horse and going through a tunnel which only has a height of 2 blocks ... minecraft lets you go through, but the player starts suffocating in the 3rd block
[VehicleFix](https://modrinth.com/mod/vehiclefix) fixed to till version 1.19.3 and there won't be any more updates from that mod since the modder left the modding scene.

now my question is if HorseBuff could implement that fix since it pretty much fits into it

**Comment by CodeF53** [comment]
I will work on this next time I work on horse buff

**Comment by CodeF53** [comment]
I have decided to link to the mod in horse buff's readme as I wouldn't want to steal from other creators who keep their stuff updated.
