### ISSUE TITLE
Suggestion: Horses in Boats

### ISSUE THREAD

**Issue by ParanormalChicken** [CodeF53/Horse-Buff#55]
Pretty self-explanatory. Horses can't get in boats, but they should be able to. Other rideable mobs can do it, so...

**Comment by mistrk7** [comment]
I'm a design freak so if I were to implement this I would make it exclusive to Rafts, since Horses would visually fit on them properly instead of clipping in the edges.

**Comment by CodeF53** [comment]
> make it exclusive to Rafts
fuck no, that would be really hard to implement

**Comment by ParanormalChicken** [comment]
there was another mod that made horses sit vertically in boats when there was more than one passenger.
also i'm pretty sure ravagers can fit in boats lol

**Comment by CodeF53** [comment]
https://modrinth.com/mod/horsebuff/version/SlE8YgP0
