### ISSUE TITLE
Horses not being able to swim while mounted

### ISSUE THREAD

**Issue by AaduMaadu** [CodeF53/Horse-Buff#56]
I have the mod enabled on my 1.20 fabric server. But when I try to get my horse across a river bank, my horse still sinks instead of floating. 

Mod config:
noWander = true
portalPatch = true
rubberBand = true
breakSpeed = true
stepHeight = true
noBuck = true
swim = true
horseHeadAngleOffset = 0
jeb_Horses = true

[pitchFade]
enabled = false
startAngle = 30
endAngle = 50
maxTransparency = 90

Mod list:
- Alternate current
- Audaki Cart Engine
- Carpet
- Carpet Extra
- Horse Buff
- armour stand editor
- brewery
- cloth config
- collective
- debugify
- fabric api
- fixedanvilrepaircost
- giantspawn
- improvedsigns
- lithium
- starlight
- the_loved_ones
- yetanotherconfiglib

**Comment by CodeF53** [comment]
Horses swimming is actually a client side feature, sorry about that. 

I will move it to the client category and update the readme
