### ISSUE TITLE
horse armor is not transparent when you're looking down

### ISSUE THREAD

**Issue by peow** [CodeF53/Horse-Buff#57]
If the horse has any armor, it is not transparent when the Player looks down

first pic: no armor
second pic: putting armor
third pic: with armor
![huge_2023-09-28_00 32 21](https://github.com/CodeF53/Horse-Buff/assets/105888751/7417e4d6-5493-4648-ba2b-85f3b22fe6b0)
![huge_2023-09-28_00 32 30](https://github.com/CodeF53/Horse-Buff/assets/105888751/f7ccda75-32d9-4ebb-a6c1-db9582bd564a)
![huge_2023-09-28_00 32 32](https://github.com/CodeF53/Horse-Buff/assets/105888751/20a369a2-1a68-4dab-be5c-7e366445ef80)

**Comment by CodeF53** [comment]
Are you using any mods that effect the game rendering?

I remember this working perfectly in vanilla and sodium before.

**Comment by CodeF53** [comment]
More likely its them editing how horse armor is rendered to add an enchantment glint to it.

While I could implement a specific per-mod fix for this, that is hard to maintain and I am lazy.

**Comment by CodeF53** [comment]
https://github.com/Fuzss/universalenchants/blob/4fc6169d1f4e642986109607449dc701ff6ae7a8/1.20/Common/src/main/java/fuzs/universalenchants/mixin/client/HorseArmorLayerMixin.java#L31C28-L31C28

This is what breaks transparency. Inorder to render things transparent it has to be on the correct render layer. 
I doubt there is even a render layer that supports the enchantment effect and transparency at the same time.
