### ISSUE TITLE
Snow golems in vehicle teleport through portals.

### ISSUE THREAD

**Issue by mrGRINCH** [CodeF53/Horse-Buff#58]
Snow golems inside of boats and mine carts are teleported through the end portal causing issues for technical minecraft.

**Comment by CodeF53** [comment]
When I have time this will be a simple fix.

Just add a check that it is a abstracthorse in https://github.com/CodeF53/Horse-Buff/blob/1.20/src/main/java/net/F53/HorseBuff/mixin/PortalHorse/OnCollideEnd.java#L20

**Comment by mrGRINCH** [comment]
Any idea when you'll have time to update? Missing having this on our server.

**Comment by CodeF53** [comment]
I will try to work on it this weekend. I am very busy with life work and other projects.

**Comment by mrGRINCH** [comment]
> I will try to work on it this weekend. I am very busy with life work and other projects.

Much appreciated!

**Comment by mrGRINCH** [comment]
Thank you for the update! Any chance you could publish a release.jar?

**Comment by CodeF53** [comment]
I noticed a small bug that remounting fails when exiting the end, so I would like to fix that first.

You can download a jar from github actions for now if you want.

**Comment by CodeF53** [comment]
https://modrinth.com/mod/horsebuff/version/2.1.3
