### ISSUE TITLE
Config changes get reset on game start

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [CodeF53/Horse-Buff#6]
**MC** 1.17.1
**Fabric** loader 0.12.5; API 0.42.1
**ClothConfig** cloth-config-5.1.40-fabric
**HorseBuff** HorseBuff-1.1.1-1.17

To reproduce:

1. Open HorseBuff.toml
2. Set: 
```
noWander = false
fairBreeds = false
```
3. Save&Close and launch the game
4. Open HorseBuff.toml again and see that the settings have been reset back to true

Alternatively, install Mod Menu and edit the values in-game, then restart the game.

Logs: https://gist.github.com/Footage2-Amply-Pounce/42ff69b2e43da55f957cfbf310ca5ee6

**Comment by CodeF53** [comment]
Fixed by commit 336938852457f38b0739c608c3a1affc65642720
