### ISSUE TITLE
Step Height and Swimming 1.19.2

### ISSUE THREAD

**Issue by myiideas** [CodeF53/Horse-Buff#60]
Extra step height and swimming not working for 1.19.2

**Comment by CodeF53** [comment]
Support for swimming was added in version [1.19.4 2.1.0](https://modrinth.com/mod/horsebuff/version/2.1.0). I don't offer support for older versions of minecraft.

I can't recreate your issue with step height. Make sure you if you are playing on a server, you have the mod installed server side as well.
