### ISSUE TITLE
add separete config for skeleton horses

### ISSUE THREAD

**Issue by peow** [CodeF53/Horse-Buff#61]
In Vanilla Minecraft you can stay underwater with a skeleton horse, however using this mod you can't do that because of the option for horses to swim, it would be interesting if the skeleton horse had a separate configuration, for example:

Horse Swimming: Yes
Skeleton Horse Swimming: No

pls make an update to 1.20.1 fabric api v0.89.3

**Comment by CodeF53** [comment]
https://modrinth.com/mod/horsebuff/version/2.1.3
