### ISSUE TITLE
Forge port permission

### ISSUE THREAD

**Issue by davidthehat** [CodeF53/Horse-Buff#62]
Hi! I would like permission to port this mod to Forge. I have some fabric modding experience and am interested in learning some Forge modding. I like this mod and think it would be a useful and interesting project.

I have already ported the horse breeding improvement for my own personal use but am interested in attempting the other features with your permission!

Thank you.

**Comment by CodeF53** [comment]
go ahead

**Comment by CinnYaBoi** [comment]
@davidthehat did you get around to porting the mod? I would love to have a 1.19.2 forge version, I am willing to comission it if you are interested (also @CodeF53 if you are interested too)
