### ISSUE TITLE
CurseForge Upload + Feature Suggestion

### ISSUE THREAD

**Issue by DarkFighter5000** [CodeF53/Horse-Buff#69]
Could you upload the mod to CurseForge?
I'd love to use this mod in an RPG modpack I'm making for me and some friends to play. I'm making the modpack on CurseForge as it's much easier to share it that way. I'm specifically looking to use it on 1.20.1, Fabric ofc.

Also I couldn't find a list of incompatibilities anywhere. I'm hoping that means that the mod is unlikely to cause issues.

The mod prevents horses from wandering completely, I think it would be neat if they were still wander but in a customizeable radious.

**Comment by CodeF53** [comment]
# No.
This mod will never be on curseforge. 
If it is ever used in any curseforge modpack I will send a cease and desist. 
Curseforge is evil and doesn't deserve any attention. 
Move to modrinth if you want to make a modpack.

**Comment by CodeF53** [comment]
Make a new github issue for your actual feature request
