### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by DeadLector** [CodeF53/Horse-Buff#70]
Make an official 1.21 update to this fantastic mod!

**Comment by histefanhere** [comment]
I've been testing the 2.1.7 alpha version on 1.21 and most things seem to be fine, there's only a visual bug with rendering horse armor:

![2024-06-21_19 12 05](https://github.com/CodeF53/Horse-Buff/assets/23431724/7e3a576c-502e-4055-bc7b-dbeb02ddd28f)

**Comment by CodeF53** [comment]
https://modrinth.com/mod/horsebuff/version/oa649YLo

@histefanhere all rendering issues I encountered are fixed now, create a new issue if you find any more.
