### ISSUE TITLE
Suggestion: Add swimming feature for camels

### ISSUE THREAD

**Issue by PlaidBonsai8922** [CodeF53/Horse-Buff#74]
Avid camel enjoyer here. Unfortunately camel no swim. Just wanted to ask if the swimming feature is possible to be added for camels since it is mountable and the fade feature works on camels already.

**Comment by GirlInPurple** [comment]
This is already in the mod, specifically in the "Client" section of the configs, its just disabled by default.
You need Mod Menu to access the config screen, and only for 1.20.2 and above, but its there.
![image](https://github.com/user-attachments/assets/99a9ca75-5ec8-40c8-98ea-43ec4d8cf29b)
