### ISSUE TITLE
Crash: Could not execute entrypoint stage 'main' due to errors (1.21-2.1.8.jar)

### ISSUE THREAD

**Issue by koyuze** [CodeF53/Horse-Buff#78]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'horsebuff' at 'net.F53.HorseBuff.HorseBuffInit'!

Fabric version 0.16.7-1.21.1
Fabric-api       0.1060+1.21.1
Cloth-config   15.0.140
Horsebuff       1.21-2.1.8

No other mods used, I was playing it before with not issues. after a recent windows update I was no longer able to play without it crashing. Not sure if that has any relevance to this issue or not. I was also playing the mod without the cloth-config before my PC updated. But now wont work with or without it.

crash report:
[crash-2024-10-15_21.00.32-client.txt](https://github.com/user-attachments/files/17388637/crash-2024-10-15_21.00.32-client.txt)

**Comment by CodeF53** [comment]
Looking at the error it looks like your config file just got corrupted
look for horsebuff's config file in your minecraft directory and delete it

**Comment by koyuze** [comment]
That was it, just a corrupted config. Thank you
